# Generated by Django 5.1 on 2024-10-10 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('pc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pc_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.IntegerField(primary_key=50, serialize=False)),
                ('productname', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('man_date', models.DateField()),
                ('man_place', models.CharField(max_length=50)),
                ('pc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_category')),
            ],
        ),
    ]
