# Generated by Django 5.1 on 2024-11-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Sid', models.IntegerField()),
                ('Semail', models.EmailField(max_length=254)),
                ('Remail', models.EmailField(max_length=254)),
            ],
        ),
    ]
